CREATE DATABASE Tuya

USE Tuya

CREATE TABLE [DBO].[Customer](
Id	INT PRIMARY KEY IDENTITY(1,1),
Nombre VARCHAR(40) NOT NULL,
Documento VARCHAR(20) NOT NULL,
Telefno VARCHAR(15),
Direccion VARCHAR(150)
)

CREATE TABLE [DBO].[Order](
Id	INT PRIMARY KEY IDENTITY(1,1),
IdCustomer INT NOT NULL,
Descripcion VARCHAR(40) NOT NULL,
FOREIGN KEY (IdCustomer) REFERENCES [DBO].[Customer](Id)
)